### ISSUE TITLE
libre2-1v5 libre2-dev for trusty don't work

### ISSUE THREAD

**Issue by edulix** [travis-ci/apt-package-whitelist#4210]
If I try to install libre2-1v5 libre2-dev in a container-based travis-ci environment with dist: trusty, I get:
 
    E: Unable to locate package libre2-1v5
    E: Unable to locate package libre2-dev
    apt-get.diagnostics
    apt-get install failed

See https://travis-ci.org/nVotesOrg/scala-js-basic-example/jobs/258125992 for an example

**Comment by striezel** [comment]
That is because the packages libre2-dev and libre2-1v5 are not available in Ubuntu 14.04 (Trusty). Those packages are only available in Ubuntu 16.04 (Xenial) or later versions of Ubuntu.

Search results for libre2-dev in trusty packages: https://packages.ubuntu.com/search?suite=trusty&searchon=names&keywords=libre2-dev
Search results for libre2-dev in xenial packages: https://packages.ubuntu.com/search?suite=xenial&searchon=names&keywords=libre2-dev
